AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Simple Add test function

Resources:
  ServerlessAPI:
    Type: AWS::Serverless::Api
    Description: "Serverless API for Add Function"
    Properties:
      Name: "api-serverless"
      StageName: "Prod"
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type'"

  AddFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.handler
      Runtime: nodejs20.x
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /add
            Method: post
            RestApiId: !Ref ServerlessAPI
